In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [5]:
df = pd.read_excel(r"C:\Users\Faiq Hilman\Downloads\london-borough-profilesV2.xlsx")
df

,Code,Area/INDICATOR,Inner/ Outer London,GLA Population Estimate 2013,GLA Household Estimate 2013,Inland Area (Hectares),Population density (per hectare) 2013,"Average Age, 2013","Proportion of population aged 0-15, 2013","Proportion of population of working-age, 2013",...,Teenage conception rate (2012),Life satisfaction score 2012-13 (out of 10),Worthwhileness score 2012-13 (out of 10),Happiness score 2012-13 (out of 10),Anxiety score 2012-13 (out of 10),Political control in council,Proportion of seats won by Conservatives in 2014 election,Proportion of seats won by Labour in 2014 election,Proportion of seats won by Lib Dems in 2014 election,Turnout at 2014 local elections
0,E09000001,City of London,Inner London,8000,4.514371e+03,290.40,27.525868,41.303887,7.948036,77.541617,...,.,8.10,8.23,7.44,x,NaN,NaN,NaN,NaN,NaN
1,E09000002,Barking and Dagenham,Outer London,195600,7.326141e+04,3610.80,54.160527,33.228935,26.072939,63.835021,...,35.4,7.06,7.57,6.97,3.3,Lab,0,100,0,38.16
2,E09000003,Barnet,Outer London,370000,1.413858e+05,8674.80,42.651374,36.896246,20.886408,65.505593,...,14.7,7.35,7.79,7.27,2.63,Cons,50.793651,42.857143,1.587302,41.1
3,E09000004,Bexley,Outer London,236500,9.470123e+04,6058.10,39.044243,38.883039,20.282830,63.146450,...,25.8,7.47,7.75,7.21,3.22,Cons,71.428571,23.809524,0,not avail
4,E09000005,Brent,Outer London,320200,1.143186e+05,4323.30,74.063670,35.262694,20.462585,68.714872,...,19.6,7.23,7.32,7.09,3.33,Lab,9.52381,88.888889,1.587302,33
5,E09000006,Bromley,Outer London,317400,1.340127e+05,15013.50,21.137655,39.844502,19.648001,62.927051,...,24.2,7.63,7.80,7.36,3.2,Cons,85,11.666667,0,not avail
6,E09000007,Camden,Inner London,228400,1.008419e+05,2178.90,104.820985,35.842413,15.632617,73.313473,...,18.1,7.22,7.37,7.13,3.25,Lab,22.222222,74.074074,1.851852,38.69
7,E09000008,Croydon,Outer London,373100,1.500539e+05,8650.40,43.129707,36.570761,21.641888,65.638589,...,28.6,7.00,7.46,7.11,3.02,Lab,42.857143,57.142857,0,38
8,E09000009,Ealing,Outer London,344900,1.268610e+05,5554.40,62.089808,35.637099,20.642035,68.216689,...,22.4,7.24,7.48,7.44,3.58,Lab,17.391304,76.811594,5.797101,41.3
9,E09000010,Enfield,Outer London,322400,1.246020e+05,8083.20,39.888486,36.062871,22.182556,65.114934,...,26.4,7.18,7.57,7.41,2.51,Lab,34.920635,65.079365,0,37.79
10,E09000011,Greenwich,Outer London,262800,1.049996e+05,4733.40,55.516088,34.737054,21.754144,67.650982,...,34.7,7.16,7.49,7.05,3.68,Lab,15.686275,84.313725,0,37.25
11,E09000012,Hackney,Inner London,256600,1.066557e+05,1904.90,134.717347,32.624060,20.513252,72.376652,...,28.8,7.07,7.42,7.02,3.61,Lab,7.017544,87.719298,5.263158,42.89
12,E09000013,Hammersmith and Fulham,Inner London,181000,7.968869e+04,1639.70,110.384364,34.933408,16.764645,73.768103,...,25.6,7.23,7.60,6.94,3.15,Lab,43.478261,56.521739,0,38
13,E09000014,Haringey,Inner London,263100,1.054593e+05,2959.80,88.883425,34.384912,19.877305,71.199466,...,33.1,7.20,7.44,7.13,3.07,Lab,0,84.210526,15.789474,38.1
14,E09000015,Harrow,Outer London,245900,8.696860e+04,5046.30,48.722544,37.695216,20.110244,65.413384,...,14.2,7.34,7.53,7.35,3.17,Lab,41.269841,53.968254,1.587302,41
15,E09000016,Havering,Outer London,242600,9.920244e+04,11235.00,21.589910,40.296140,18.781558,62.788014,...,26.4,7.40,7.65,7.24,3.17,No Overall Control,40.740741,1.851852,0,43
16,E09000017,Hillingdon,Outer London,287500,1.046508e+05,11570.10,24.851919,36.171629,20.911751,66.121424,...,27.7,7.35,7.63,7.34,3.34,Cons,64.615385,35.384615,0,35.76
17,E09000018,Hounslow,Outer London,264300,9.884074e+04,5597.80,47.209459,35.263763,20.616902,68.542073,...,30.4,7.30,7.60,7.29,3.51,Lab,18.333333,81.666667,0,36.8
18,E09000019,Islington,Inner London,215900,9.761628e+04,1485.70,145.324910,34.419467,15.863559,75.457376,...,30.1,7.08,7.22,6.85,3.74,Lab,0,97.916667,0,38.4
19,E09000020,Kensington and Chelsea,Inner London,155700,7.721090e+04,1212.40,128.427401,38.308554,15.908516,70.878237,...,17.7,7.68,7.92,7.51,3.06,Cons,74,24,2,not avail
20,E09000021,Kingston upon Thames,Outer London,166400,6.578263e+04,3726.10,44.660475,36.885957,18.994951,67.980436,...,20,7.29,7.45,7.18,3.23,Cons,58.333333,4.166667,37.5,not avail
21,E09000022,Lambeth,Inner London,313800,1.345125e+05,2681.00,117.055632,33.862641,17.899970,74.455090,...,33.2,7.09,7.40,6.97,3.69,Lab,4.761905,93.650794,0,32
22,E09000023,Lewisham,Inner London,286000,1.204394e+05,3514.90,81.366697,34.540168,20.620499,69.996836,...,42,7.23,7.71,7.13,3.35,Lab,0,98.148148,0,37.2
23,E09000024,Merton,Outer London,205400,8.104764e+04,3762.50,54.603478,36.262610,20.203379,67.896608,...,25.5,7.18,7.54,7.13,3.59,Lab,33.333333,60,1.666667,41
24,E09000025,Newham,Inner London,323400,1.077933e+05,3619.80,89.338992,31.423439,22.508503,70.809763,...,24.1,7.22,7.51,7.32,3.36,Lab,0,100,0,40.62
25,E09000026,Redbridge,Outer London,289900,1.030537e+05,5641.90,51.374341,35.531757,22.684198,65.238253,...,16.2,7.28,7.44,7.34,3.12,Lab,39.68254,55.555556,4.761905,39.7
26,E09000027,Richmond upon Thames,Outer London,191300,8.135316e+04,5740.70,33.331460,38.290205,20.202975,65.548776,...,19.9,7.42,7.69,7.33,3.56,Cons,72.222222,0,27.777778,46.3
27,E09000028,Southwark,Inner London,298400,1.246139e+05,2886.20,103.403127,33.754401,18.507644,73.722633,...,31.8,7.27,7.68,7.20,3.28,Lab,3.174603,76.190476,20.634921,not avail
28,E09000029,Sutton,Outer London,196400,8.074848e+04,4384.70,44.802887,38.310437,20.151661,64.951011,...,25.8,7.25,7.57,7.13,3.34,Lib Dem,16.666667,0,83.333333,42.2
29,E09000030,Tower Hamlets,Inner London,271100,1.092805e+05,1978.10,137.067542,31.064282,19.602621,74.531880,...,24.3,7.28,7.56,7.32,2.93,Tower Hamlets First,15.555556,44.444444,0,not avail
30,E09000031,Waltham Forest,Outer London,267700,1.005245e+05,3880.80,68.970286,34.502988,21.784829,68.105760,...,29.9,7.24,7.72,7.26,2.99,Lab,26.666667,73.333333,0,not avail
31,E09000032,Wandsworth,Inner London,311800,1.315620e+05,3426.40,91.009107,34.414955,17.342442,73.693151,...,25.5,7.23,7.55,7.28,3.55,Cons,68.333333,31.666667,0,not avail
32,E09000033,Westminster,Inner London,226600,1.085501e+05,2148.70,105.457732,36.729055,14.781940,73.924420,...,21.2,7.09,7.44,7.09,3.58,Cons,73.333333,26.666667,0,not avail
33,E13000001,Inner London,.,3339900,1.408739e+06,31929.20,104.604284,34.094128,18.399747,72.928004,...,28.5,7.21,7.52,7.15,3.36,.,23.709902,69.456067,3.76569,not avail
34,E13000002,Outer London,NaN,5100200,1.966369e+06,125423.60,40.663753,36.608313,20.975104,65.989008,...,24.5,7.28,7.58,7.25,3.21,.,39.153439,49.118166,7.848325,not avail
35,E12000007,London,NaN,8440100,3.375108e+06,157214.70,53.685369,35.613397,19.955981,68.734914,...,25.9,7.26,7.56,7.21,3.27,.,33.171259,56.996218,6.266883,not avail
36,E92000001,England,NaN,53493729,2.254290e+07,13027866.98,4.069162,39.442770,18.937222,64.132742,...,27.7,7.44,7.68,7.28,3.05,.,.,.,.,.
37,K02000001,United Kingdom,NaN,63705030,2.706534e+07,24309424.52,2.561228,39.553318,18.811058,64.171517,...,.,7.45,7.69,7.29,3.03,.,.,.,.,.

In [8]:
df1 = df.apply(pd.to_numeric, errors='coerce')
df1 = df.dropna(axis=1, how='all')
df1

,Code,Area/INDICATOR,Inner/ Outer London,GLA Population Estimate 2013,GLA Household Estimate 2013,Inland Area (Hectares),Population density (per hectare) 2013,"Average Age, 2013","Proportion of population aged 0-15, 2013","Proportion of population of working-age, 2013",...,Teenage conception rate (2012),Life satisfaction score 2012-13 (out of 10),Worthwhileness score 2012-13 (out of 10),Happiness score 2012-13 (out of 10),Anxiety score 2012-13 (out of 10),Political control in council,Proportion of seats won by Conservatives in 2014 election,Proportion of seats won by Labour in 2014 election,Proportion of seats won by Lib Dems in 2014 election,Turnout at 2014 local elections
0,E09000001,City of London,Inner London,8000,4.514371e+03,290.40,27.525868,41.303887,7.948036,77.541617,...,.,8.10,8.23,7.44,x,NaN,NaN,NaN,NaN,NaN
1,E09000002,Barking and Dagenham,Outer London,195600,7.326141e+04,3610.80,54.160527,33.228935,26.072939,63.835021,...,35.4,7.06,7.57,6.97,3.3,Lab,0,100,0,38.16
2,E09000003,Barnet,Outer London,370000,1.413858e+05,8674.80,42.651374,36.896246,20.886408,65.505593,...,14.7,7.35,7.79,7.27,2.63,Cons,50.793651,42.857143,1.587302,41.1
3,E09000004,Bexley,Outer London,236500,9.470123e+04,6058.10,39.044243,38.883039,20.282830,63.146450,...,25.8,7.47,7.75,7.21,3.22,Cons,71.428571,23.809524,0,not avail
4,E09000005,Brent,Outer London,320200,1.143186e+05,4323.30,74.063670,35.262694,20.462585,68.714872,...,19.6,7.23,7.32,7.09,3.33,Lab,9.52381,88.888889,1.587302,33
5,E09000006,Bromley,Outer London,317400,1.340127e+05,15013.50,21.137655,39.844502,19.648001,62.927051,...,24.2,7.63,7.80,7.36,3.2,Cons,85,11.666667,0,not avail
6,E09000007,Camden,Inner London,228400,1.008419e+05,2178.90,104.820985,35.842413,15.632617,73.313473,...,18.1,7.22,7.37,7.13,3.25,Lab,22.222222,74.074074,1.851852,38.69
7,E09000008,Croydon,Outer London,373100,1.500539e+05,8650.40,43.129707,36.570761,21.641888,65.638589,...,28.6,7.00,7.46,7.11,3.02,Lab,42.857143,57.142857,0,38
8,E09000009,Ealing,Outer London,344900,1.268610e+05,5554.40,62.089808,35.637099,20.642035,68.216689,...,22.4,7.24,7.48,7.44,3.58,Lab,17.391304,76.811594,5.797101,41.3
9,E09000010,Enfield,Outer London,322400,1.246020e+05,8083.20,39.888486,36.062871,22.182556,65.114934,...,26.4,7.18,7.57,7.41,2.51,Lab,34.920635,65.079365,0,37.79
10,E09000011,Greenwich,Outer London,262800,1.049996e+05,4733.40,55.516088,34.737054,21.754144,67.650982,...,34.7,7.16,7.49,7.05,3.68,Lab,15.686275,84.313725,0,37.25
11,E09000012,Hackney,Inner London,256600,1.066557e+05,1904.90,134.717347,32.624060,20.513252,72.376652,...,28.8,7.07,7.42,7.02,3.61,Lab,7.017544,87.719298,5.263158,42.89
12,E09000013,Hammersmith and Fulham,Inner London,181000,7.968869e+04,1639.70,110.384364,34.933408,16.764645,73.768103,...,25.6,7.23,7.60,6.94,3.15,Lab,43.478261,56.521739,0,38
13,E09000014,Haringey,Inner London,263100,1.054593e+05,2959.80,88.883425,34.384912,19.877305,71.199466,...,33.1,7.20,7.44,7.13,3.07,Lab,0,84.210526,15.789474,38.1
14,E09000015,Harrow,Outer London,245900,8.696860e+04,5046.30,48.722544,37.695216,20.110244,65.413384,...,14.2,7.34,7.53,7.35,3.17,Lab,41.269841,53.968254,1.587302,41
15,E09000016,Havering,Outer London,242600,9.920244e+04,11235.00,21.589910,40.296140,18.781558,62.788014,...,26.4,7.40,7.65,7.24,3.17,No Overall Control,40.740741,1.851852,0,43
16,E09000017,Hillingdon,Outer London,287500,1.046508e+05,11570.10,24.851919,36.171629,20.911751,66.121424,...,27.7,7.35,7.63,7.34,3.34,Cons,64.615385,35.384615,0,35.76
17,E09000018,Hounslow,Outer London,264300,9.884074e+04,5597.80,47.209459,35.263763,20.616902,68.542073,...,30.4,7.30,7.60,7.29,3.51,Lab,18.333333,81.666667,0,36.8
18,E09000019,Islington,Inner London,215900,9.761628e+04,1485.70,145.324910,34.419467,15.863559,75.457376,...,30.1,7.08,7.22,6.85,3.74,Lab,0,97.916667,0,38.4
19,E09000020,Kensington and Chelsea,Inner London,155700,7.721090e+04,1212.40,128.427401,38.308554,15.908516,70.878237,...,17.7,7.68,7.92,7.51,3.06,Cons,74,24,2,not avail
20,E09000021,Kingston upon Thames,Outer London,166400,6.578263e+04,3726.10,44.660475,36.885957,18.994951,67.980436,...,20,7.29,7.45,7.18,3.23,Cons,58.333333,4.166667,37.5,not avail
21,E09000022,Lambeth,Inner London,313800,1.345125e+05,2681.00,117.055632,33.862641,17.899970,74.455090,...,33.2,7.09,7.40,6.97,3.69,Lab,4.761905,93.650794,0,32
22,E09000023,Lewisham,Inner London,286000,1.204394e+05,3514.90,81.366697,34.540168,20.620499,69.996836,...,42,7.23,7.71,7.13,3.35,Lab,0,98.148148,0,37.2
23,E09000024,Merton,Outer London,205400,8.104764e+04,3762.50,54.603478,36.262610,20.203379,67.896608,...,25.5,7.18,7.54,7.13,3.59,Lab,33.333333,60,1.666667,41
24,E09000025,Newham,Inner London,323400,1.077933e+05,3619.80,89.338992,31.423439,22.508503,70.809763,...,24.1,7.22,7.51,7.32,3.36,Lab,0,100,0,40.62
25,E09000026,Redbridge,Outer London,289900,1.030537e+05,5641.90,51.374341,35.531757,22.684198,65.238253,...,16.2,7.28,7.44,7.34,3.12,Lab,39.68254,55.555556,4.761905,39.7
26,E09000027,Richmond upon Thames,Outer London,191300,8.135316e+04,5740.70,33.331460,38.290205,20.202975,65.548776,...,19.9,7.42,7.69,7.33,3.56,Cons,72.222222,0,27.777778,46.3
27,E09000028,Southwark,Inner London,298400,1.246139e+05,2886.20,103.403127,33.754401,18.507644,73.722633,...,31.8,7.27,7.68,7.20,3.28,Lab,3.174603,76.190476,20.634921,not avail
28,E09000029,Sutton,Outer London,196400,8.074848e+04,4384.70,44.802887,38.310437,20.151661,64.951011,...,25.8,7.25,7.57,7.13,3.34,Lib Dem,16.666667,0,83.333333,42.2
29,E09000030,Tower Hamlets,Inner London,271100,1.092805e+05,1978.10,137.067542,31.064282,19.602621,74.531880,...,24.3,7.28,7.56,7.32,2.93,Tower Hamlets First,15.555556,44.444444,0,not avail
30,E09000031,Waltham Forest,Outer London,267700,1.005245e+05,3880.80,68.970286,34.502988,21.784829,68.105760,...,29.9,7.24,7.72,7.26,2.99,Lab,26.666667,73.333333,0,not avail
31,E09000032,Wandsworth,Inner London,311800,1.315620e+05,3426.40,91.009107,34.414955,17.342442,73.693151,...,25.5,7.23,7.55,7.28,3.55,Cons,68.333333,31.666667,0,not avail
32,E09000033,Westminster,Inner London,226600,1.085501e+05,2148.70,105.457732,36.729055,14.781940,73.924420,...,21.2,7.09,7.44,7.09,3.58,Cons,73.333333,26.666667,0,not avail
33,E13000001,Inner London,.,3339900,1.408739e+06,31929.20,104.604284,34.094128,18.399747,72.928004,...,28.5,7.21,7.52,7.15,3.36,.,23.709902,69.456067,3.76569,not avail
34,E13000002,Outer London,NaN,5100200,1.966369e+06,125423.60,40.663753,36.608313,20.975104,65.989008,...,24.5,7.28,7.58,7.25,3.21,.,39.153439,49.118166,7.848325,not avail
35,E12000007,London,NaN,8440100,3.375108e+06,157214.70,53.685369,35.613397,19.955981,68.734914,...,25.9,7.26,7.56,7.21,3.27,.,33.171259,56.996218,6.266883,not avail
36,E92000001,England,NaN,53493729,2.254290e+07,13027866.98,4.069162,39.442770,18.937222,64.132742,...,27.7,7.44,7.68,7.28,3.05,.,.,.,.,.
37,K02000001,United Kingdom,NaN,63705030,2.706534e+07,24309424.52,2.561228,39.553318,18.811058,64.171517,...,.,7.45,7.69,7.29,3.03,.,.,.,.,.

In [11]:
df1.fillna(0)
df1

,Code,Area/INDICATOR,Inner/ Outer London,GLA Population Estimate 2013,GLA Household Estimate 2013,Inland Area (Hectares),Population density (per hectare) 2013,"Average Age, 2013","Proportion of population aged 0-15, 2013","Proportion of population of working-age, 2013",...,Teenage conception rate (2012),Life satisfaction score 2012-13 (out of 10),Worthwhileness score 2012-13 (out of 10),Happiness score 2012-13 (out of 10),Anxiety score 2012-13 (out of 10),Political control in council,Proportion of seats won by Conservatives in 2014 election,Proportion of seats won by Labour in 2014 election,Proportion of seats won by Lib Dems in 2014 election,Turnout at 2014 local elections
0,E09000001,City of London,Inner London,8000,4.514371e+03,290.40,27.525868,41.303887,7.948036,77.541617,...,.,8.10,8.23,7.44,x,NaN,NaN,NaN,NaN,NaN
1,E09000002,Barking and Dagenham,Outer London,195600,7.326141e+04,3610.80,54.160527,33.228935,26.072939,63.835021,...,35.4,7.06,7.57,6.97,3.3,Lab,0,100,0,38.16
2,E09000003,Barnet,Outer London,370000,1.413858e+05,8674.80,42.651374,36.896246,20.886408,65.505593,...,14.7,7.35,7.79,7.27,2.63,Cons,50.793651,42.857143,1.587302,41.1
3,E09000004,Bexley,Outer London,236500,9.470123e+04,6058.10,39.044243,38.883039,20.282830,63.146450,...,25.8,7.47,7.75,7.21,3.22,Cons,71.428571,23.809524,0,not avail
4,E09000005,Brent,Outer London,320200,1.143186e+05,4323.30,74.063670,35.262694,20.462585,68.714872,...,19.6,7.23,7.32,7.09,3.33,Lab,9.52381,88.888889,1.587302,33
5,E09000006,Bromley,Outer London,317400,1.340127e+05,15013.50,21.137655,39.844502,19.648001,62.927051,...,24.2,7.63,7.80,7.36,3.2,Cons,85,11.666667,0,not avail
6,E09000007,Camden,Inner London,228400,1.008419e+05,2178.90,104.820985,35.842413,15.632617,73.313473,...,18.1,7.22,7.37,7.13,3.25,Lab,22.222222,74.074074,1.851852,38.69
7,E09000008,Croydon,Outer London,373100,1.500539e+05,8650.40,43.129707,36.570761,21.641888,65.638589,...,28.6,7.00,7.46,7.11,3.02,Lab,42.857143,57.142857,0,38
8,E09000009,Ealing,Outer London,344900,1.268610e+05,5554.40,62.089808,35.637099,20.642035,68.216689,...,22.4,7.24,7.48,7.44,3.58,Lab,17.391304,76.811594,5.797101,41.3
9,E09000010,Enfield,Outer London,322400,1.246020e+05,8083.20,39.888486,36.062871,22.182556,65.114934,...,26.4,7.18,7.57,7.41,2.51,Lab,34.920635,65.079365,0,37.79
10,E09000011,Greenwich,Outer London,262800,1.049996e+05,4733.40,55.516088,34.737054,21.754144,67.650982,...,34.7,7.16,7.49,7.05,3.68,Lab,15.686275,84.313725,0,37.25
11,E09000012,Hackney,Inner London,256600,1.066557e+05,1904.90,134.717347,32.624060,20.513252,72.376652,...,28.8,7.07,7.42,7.02,3.61,Lab,7.017544,87.719298,5.263158,42.89
12,E09000013,Hammersmith and Fulham,Inner London,181000,7.968869e+04,1639.70,110.384364,34.933408,16.764645,73.768103,...,25.6,7.23,7.60,6.94,3.15,Lab,43.478261,56.521739,0,38
13,E09000014,Haringey,Inner London,263100,1.054593e+05,2959.80,88.883425,34.384912,19.877305,71.199466,...,33.1,7.20,7.44,7.13,3.07,Lab,0,84.210526,15.789474,38.1
14,E09000015,Harrow,Outer London,245900,8.696860e+04,5046.30,48.722544,37.695216,20.110244,65.413384,...,14.2,7.34,7.53,7.35,3.17,Lab,41.269841,53.968254,1.587302,41
15,E09000016,Havering,Outer London,242600,9.920244e+04,11235.00,21.589910,40.296140,18.781558,62.788014,...,26.4,7.40,7.65,7.24,3.17,No Overall Control,40.740741,1.851852,0,43
16,E09000017,Hillingdon,Outer London,287500,1.046508e+05,11570.10,24.851919,36.171629,20.911751,66.121424,...,27.7,7.35,7.63,7.34,3.34,Cons,64.615385,35.384615,0,35.76
17,E09000018,Hounslow,Outer London,264300,9.884074e+04,5597.80,47.209459,35.263763,20.616902,68.542073,...,30.4,7.30,7.60,7.29,3.51,Lab,18.333333,81.666667,0,36.8
18,E09000019,Islington,Inner London,215900,9.761628e+04,1485.70,145.324910,34.419467,15.863559,75.457376,...,30.1,7.08,7.22,6.85,3.74,Lab,0,97.916667,0,38.4
19,E09000020,Kensington and Chelsea,Inner London,155700,7.721090e+04,1212.40,128.427401,38.308554,15.908516,70.878237,...,17.7,7.68,7.92,7.51,3.06,Cons,74,24,2,not avail
20,E09000021,Kingston upon Thames,Outer London,166400,6.578263e+04,3726.10,44.660475,36.885957,18.994951,67.980436,...,20,7.29,7.45,7.18,3.23,Cons,58.333333,4.166667,37.5,not avail
21,E09000022,Lambeth,Inner London,313800,1.345125e+05,2681.00,117.055632,33.862641,17.899970,74.455090,...,33.2,7.09,7.40,6.97,3.69,Lab,4.761905,93.650794,0,32
22,E09000023,Lewisham,Inner London,286000,1.204394e+05,3514.90,81.366697,34.540168,20.620499,69.996836,...,42,7.23,7.71,7.13,3.35,Lab,0,98.148148,0,37.2
23,E09000024,Merton,Outer London,205400,8.104764e+04,3762.50,54.603478,36.262610,20.203379,67.896608,...,25.5,7.18,7.54,7.13,3.59,Lab,33.333333,60,1.666667,41
24,E09000025,Newham,Inner London,323400,1.077933e+05,3619.80,89.338992,31.423439,22.508503,70.809763,...,24.1,7.22,7.51,7.32,3.36,Lab,0,100,0,40.62
25,E09000026,Redbridge,Outer London,289900,1.030537e+05,5641.90,51.374341,35.531757,22.684198,65.238253,...,16.2,7.28,7.44,7.34,3.12,Lab,39.68254,55.555556,4.761905,39.7
26,E09000027,Richmond upon Thames,Outer London,191300,8.135316e+04,5740.70,33.331460,38.290205,20.202975,65.548776,...,19.9,7.42,7.69,7.33,3.56,Cons,72.222222,0,27.777778,46.3
27,E09000028,Southwark,Inner London,298400,1.246139e+05,2886.20,103.403127,33.754401,18.507644,73.722633,...,31.8,7.27,7.68,7.20,3.28,Lab,3.174603,76.190476,20.634921,not avail
28,E09000029,Sutton,Outer London,196400,8.074848e+04,4384.70,44.802887,38.310437,20.151661,64.951011,...,25.8,7.25,7.57,7.13,3.34,Lib Dem,16.666667,0,83.333333,42.2
29,E09000030,Tower Hamlets,Inner London,271100,1.092805e+05,1978.10,137.067542,31.064282,19.602621,74.531880,...,24.3,7.28,7.56,7.32,2.93,Tower Hamlets First,15.555556,44.444444,0,not avail
30,E09000031,Waltham Forest,Outer London,267700,1.005245e+05,3880.80,68.970286,34.502988,21.784829,68.105760,...,29.9,7.24,7.72,7.26,2.99,Lab,26.666667,73.333333,0,not avail
31,E09000032,Wandsworth,Inner London,311800,1.315620e+05,3426.40,91.009107,34.414955,17.342442,73.693151,...,25.5,7.23,7.55,7.28,3.55,Cons,68.333333,31.666667,0,not avail
32,E09000033,Westminster,Inner London,226600,1.085501e+05,2148.70,105.457732,36.729055,14.781940,73.924420,...,21.2,7.09,7.44,7.09,3.58,Cons,73.333333,26.666667,0,not avail
33,E13000001,Inner London,.,3339900,1.408739e+06,31929.20,104.604284,34.094128,18.399747,72.928004,...,28.5,7.21,7.52,7.15,3.36,.,23.709902,69.456067,3.76569,not avail
34,E13000002,Outer London,NaN,5100200,1.966369e+06,125423.60,40.663753,36.608313,20.975104,65.989008,...,24.5,7.28,7.58,7.25,3.21,.,39.153439,49.118166,7.848325,not avail
35,E12000007,London,NaN,8440100,3.375108e+06,157214.70,53.685369,35.613397,19.955981,68.734914,...,25.9,7.26,7.56,7.21,3.27,.,33.171259,56.996218,6.266883,not avail
36,E92000001,England,NaN,53493729,2.254290e+07,13027866.98,4.069162,39.442770,18.937222,64.132742,...,27.7,7.44,7.68,7.28,3.05,.,.,.,.,.
37,K02000001,United Kingdom,NaN,63705030,2.706534e+07,24309424.52,2.561228,39.553318,18.811058,64.171517,...,.,7.45,7.69,7.29,3.03,.,.,.,.,.

In [12]:
from sklearn.metrics import euclidean_distances
distMatrix = euclidean_distances(df1, df1)

ValueError: could not convert string to float: 'E09000001'